## Complete Text Processing

### **B. Preprocessing and Cleaning**
- Lower case
- Contraction to Expansion
- Emails removal and counts
- URLs removal and counts
- Removal of RT
- Removal of Special Characters
- Removal of multiple spaces
- Removal of HTML tags
- Removal of accented characters
- Removal of Stop Words
- Conversion into base form of words
- Common Occuring words Removal
- Rare Occuring words Removal
- Word Cloud
- Spelling Correction
- Tokenization
- Lemmatization
- Detecting Entities using NER
- Noun Detection
- N-Gram, Word Count, Lemmatization and POS Tagging
- Using Inbuilt Sentiment Classifier
- Sentence Translation
- Language Detection

### 9. Lower Case Conversion

In [2]:
import pandas as pd
import numpy as np
import re

In [3]:
url = 'https://github.com/laxmimerit/All-CSV-ML-Data-Files-Download/raw/master/twitter4000.csv'
df = pd.read_csv(url)

In [4]:
x = 'IS bored and wants to watch a movie        any suggestions '
x.lower()

re.sub(r'\s+', ' ', x).lower()

'is bored and wants to watch a movie any suggestions '

In [5]:
# we will make the changes on original column itself as we are preprocessing the data.
df['tweets']=df['tweets'].apply(lambda x: re.sub('\s+',' ',x).lower())

In [6]:
df.head()

                                              tweets  sentiment
0  is bored and wants to watch a movie any sugges...          0
1            back in miami. waiting to unboard ship           0
2  @misskpey awwww dnt dis brng bak memoriessss, ...          0
3                   ughhh i am so tired blahhhhhhhhh          0
4  @mandagoforth me bad! it's funny though. zacha...          0

### 10. Contraction to Expansion

In [7]:
import json

contractions = json.load(open('data/contractions.json'))

In [8]:
contractions.get("don't")

'do not'

In [9]:
# Dictionary lookup: .get(key, default) returns the expanded word if it exists,
# otherwise it keeps the original word to prevent errors.
x = "don't mess with me. I'm done with this stuff."
[contractions.get(word, word) for word in x.split()]

['do not', 'mess', 'with', 'me.', "I'm", 'done', 'with', 'this', 'stuff.']

In [10]:
[contractions.get(word.lower(), word) for word in x.split()]

['do not', 'mess', 'with', 'me.', 'i am', 'done', 'with', 'this', 'stuff.']

In [11]:
" ".join([contractions.get(word.lower(), word) for word in x.split()])

'do not mess with me. i am done with this stuff.'

In [12]:
df['tweets']=df['tweets'].apply(lambda x: " ".join([contractions.get(word.lower(), word) for word in str(x).split()])) #str(x)is imp as without str python is thinking that it's a method and not string.

In [13]:
df

                                                 tweets  sentiment
0     is bored and wants to watch a movie any sugges...          0
1                back in miami. waiting to unboard ship          0
2     @misskpey awwww dnt this bring back at keyboar...          0
3                      ughhh i am so tired blahhhhhhhhh          0
4     @mandagoforth me bad! it is funny though. zach...          0
...                                                 ...        ...
3995                                   i just graduated          1
3996            templating works; it all has to be done          1
3997                    mommy just brought me starbucks          1
3998  @omarepps watching you on a house re-run...lov...          1
3999  thanks for trying to make me smile i will make...          1

[4000 rows x 2 columns]

In [14]:
df[df['tweets'].str.contains("don't")]

                                                 tweets  sentiment
482   making myself ready for school...don't feel li...          0
1259  @dougiemcfly own,don't do that,i'm sure it was...          0
3729  @worldofhiglet i do not think it makes you see...          1

### 11. Count and Remove Emails

In [15]:
x = 'contact me at rutujakumbhar@gmail.com and info@rutuja@gmail.com'

pattern = r'\w+@\w+.\w+'
result = re.findall(pattern=pattern, string=x)
print(result)

['rutujakumbhar@gmail.com', 'info@rutuja@gmail']

In [16]:
x = 'contact me at rutujakumbhar@gmail.com and info@rutuja@gmail.co.in'

pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
result = re.findall(pattern=pattern, string=x)
print(result)

['rutujakumbhar@gmail.com', 'rutuja@gmail.co.in']

In [17]:
df['emails'] = df['emails'] =df['tweets'].apply(lambda x: ",".join(re.findall(pattern=pattern, string=x)))

In [18]:
df['emails'].value_counts()

emails
                               3999
markbradbury_16@hotmail.com       1
Name: count, dtype: int64

In [19]:
x = ''
x.count(',')+1 if len(x)>0 else 0

0

In [20]:
df['emails'].value_counts()

emails
                               3999
markbradbury_16@hotmail.com       1
Name: count, dtype: int64

In [21]:
df['emails_count'] = df['emails'].apply(lambda x: x.count(',')+1 if len(x)>0 else 0)

In [22]:
df['emails_count'].value_counts()

emails_count
0    3999
1       1
Name: count, dtype: int64

In [23]:
df['tweets'] = df['tweets'].apply(lambda x: re.sub(pattern, '', x))

In [24]:
df.head()

,tweets,sentiment,emails,emails_count
0,is bored and wants to watch a movie any sugges...,0,,0
1,back in miami. waiting to unboard ship,0,,0
2,@misskpey awwww dnt this bring back at keyboar...,0,,0
3,ughhh i am so tired blahhhhhhhhh,0,,0
4,@mandagoforth me bad! it is funny though. zach...,0,,0

### 12. Count and Remove URLs

In [25]:
x='Check this link: https://rutujakumbhar.com and www.rutujakumbhar.com'
pattern=r"http\S+|www\.\S+"
re.findall(pattern,x)

['https://rutujakumbhar.com', 'www.rutujakumbhar.com']

In [26]:
df['urls']=df['tweets'].apply(lambda x: re.findall(pattern,x))

In [27]:
df['urls'].value_counts()
df['urls_count']=df['urls'].apply(lambda x: len(x))

In [28]:
df[df['urls_count']>0].head()

,tweets,sentiment,emails,emails_count,urls,urls_count
16,@brianquest i made 1 fo you 2: http://bit.ly/e...,0,,0,[http://bit.ly/eid8a],1
98,heading to work http://twitpic.com/4eojz,0,,0,[http://twitpic.com/4eojz],1
99,@blondeblogger http://twitpic.com/4w8hk - i am...,0,,0,[http://twitpic.com/4w8hk],1
144,i miss you â« http://blip.fm/~8lc2f,0,,0,[http://blip.fm/~8lc2f],1
183,photo: miss germany http://tumblr.com/xf825f012,0,,0,[http://tumblr.com/xf825f012],1

In [29]:
df['tweets']=df['tweets'].apply(lambda x: re.sub(pattern,'',x))

In [30]:
df[df['urls_count']>0].head()

,tweets,sentiment,emails,emails_count,urls,urls_count
16,@brianquest i made 1 fo you 2: i tried but it...,0,,0,[http://bit.ly/eid8a],1
98,heading to work,0,,0,[http://twitpic.com/4eojz],1
99,@blondeblogger - i am so sad this is so blurry!,0,,0,[http://twitpic.com/4w8hk],1
144,i miss you â«,0,,0,[http://blip.fm/~8lc2f],1
183,photo: miss germany,0,,0,[http://tumblr.com/xf825f012],1

### 13. Remove RT (Retweet)

In [31]:
x = 'RT @rutujakumbhar: this is a retweet'

In [32]:
df

,tweets,sentiment,emails,emails_count,urls,urls_count
0,is bored and wants to watch a movie any sugges...,0,,0,[],0
1,back in miami. waiting to unboard ship,0,,0,[],0
2,@misskpey awwww dnt this bring back at keyboar...,0,,0,[],0
3,ughhh i am so tired blahhhhhhhhh,0,,0,[],0
4,@mandagoforth me bad! it is funny though. zach...,0,,0,[],0
...,...,...,...,...,...,...
3995,i just graduated,1,,0,[],0
3996,templating works; it all has to be done,1,,0,[],0
3997,mommy just brought me starbucks,1,,0,[],0
3998,@omarepps watching you on a house re-run...lov...,1,,0,[],0
3999,thanks for trying to make me smile i will make...,1,,0,[],0

In [33]:
pattern = r'\bRT @\w+'
re.findall(pattern,x)

['RT @rutujakumbhar']

In [34]:
bool (len(re.findall(pattern,x)))

True

In [35]:
df['is_retweet'] =df['tweets'].apply(lambda x: bool(len(re.findall(pattern,x))))

In [36]:
df['is_retweet'].sum()

np.int64(0)

In [37]:
#How to remove the retweet
df['tweet'] =df['tweets'].apply(lambda x: re.sub(pattern,'',x))

### 14. Remove HTML tags

In [38]:
# !pip install beautifulsoup4==3.2.2

In [39]:
x = '<meta property="og:title" content="How to Become a Successful Machine Learning Engineer - KGP Talkie" />'

In [40]:
from bs4 import BeautifulSoup

In [41]:
soup = BeautifulSoup(x, 'lxml')

In [42]:
soup

In [43]:
soup.find('meta')['content']

'How to Become a Successful Machine Learning Engineer - KGP Talkie'

In [44]:
x = '<p>To become a successful machine learning engineer, you need to have a solid foundation of technical skills. This includes proficiency in programming languages like Python and R, as well as knowledge of machine learning frameworks like TensorFlow and PyTorch. Additionally, you should be familiar with data analysis tools like SQL and Excel.</p>'

soup = BeautifulSoup(x, 'lxml')

In [45]:
soup.get_text()

'To become a successful machine learning engineer, you need to have a solid foundation of technical skills. This includes proficiency in programming languages like Python and R, as well as knowledge of machine learning frameworks like TensorFlow and PyTorch. Additionally, you should be familiar with data analysis tools like SQL and Excel.'

In [46]:
df['tweets'] = df['tweets'].apply(lambda x: BeautifulSoup('<p>'+x+'</p>', 'lxml').get_text())

In [47]:
df.head()

,tweets,sentiment,emails,emails_count,urls,urls_count,is_retweet,tweet
0,is bored and wants to watch a movie any sugges...,0,,0,[],0,False,is bored and wants to watch a movie any sugges...
1,back in miami. waiting to unboard ship,0,,0,[],0,False,back in miami. waiting to unboard ship
2,@misskpey awwww dnt this bring back at keyboar...,0,,0,[],0,False,@misskpey awwww dnt this bring back at keyboar...
3,ughhh i am so tired blahhhhhhhhh,0,,0,[],0,False,ughhh i am so tired blahhhhhhhhh
4,@mandagoforth me bad! it is funny though. zach...,0,,0,[],0,False,@mandagoforth me bad! it is funny though. zach...

### 15. Remove Accented Chars

In [ ]:
# marks added to letters to indicate changes in pronunciation, stress, or meaning. (e.g., é, á).

import unicodedata

x = 'à, è, ì, ò, ù, À, È, Ì, Ò, Ù'

unicodedata.normalize('NFKD',x).encode('ascii','ignore').decode('utf-8','ignore')

#Decompose characters into base letter + accent (e.g., 'à' -> 'a' + '`')
#normalized = unicodedata.normalize('NFKD', x)

# Filter out non-ASCII characters (the accents) and convert back to string
#stripped = normalized.encode('ascii', 'ignore').decode('utf-8')

'a, e, i, o, u, A, E, I, O, U'

In [53]:
df['tweets']=df['tweets'].apply(lambda x:unicodedata.normalize('NFKD',x).encode('ascii','ignore').decode('utf-8','ignore'))

### 16. Remove Chars removal or Punctual removal

In [54]:
x = '@misskpey awwww dnt this bring back at #keyboard!'

pattern = r'@\w+'
re.findall(pattern, x)
x = re.sub(pattern, '', x).strip()
x

'awwww dnt this bring back at #keyboard!'