## Complete Text Processing

### **B. Preprocessing and Cleaning**
- Lower case
- Contraction to Expansion
- Emails removal and counts
- URLs removal and counts
- Removal of RT
- Removal of Special Characters
- Removal of multiple spaces
- Removal of HTML tags
- Removal of accented characters
- Removal of Stop Words
- Conversion into base form of words
- Common Occuring words Removal
- Rare Occuring words Removal
- Word Cloud
- Spelling Correction
- Tokenization
- Lemmatization
- Detecting Entities using NER
- Noun Detection
- N-Gram, Word Count, Lemmatization and POS Tagging
- Using Inbuilt Sentiment Classifier
- Sentence Translation
- Language Detection

### 9. Lower Case Conversion

In [ ]:
import pandas as pd
import numpy as np
import re

In [123]:
url = 'https://github.com/laxmimerit/All-CSV-ML-Data-Files-Download/raw/master/twitter4000.csv'
df = pd.read_csv(url)

In [124]:
x = 'IS bored and wants to watch a movie        any suggestions '
x.lower()

re.sub(r'\s+', ' ', x).lower()

'is bored and wants to watch a movie any suggestions '

In [125]:
# we will make the changes on original column itself as we are preprocessing the data.
df['tweets']=df['tweets'].apply(lambda x: re.sub('\s+',' ',x).lower())

In [126]:
df.head()

                                              tweets  sentiment
0  is bored and wants to watch a movie any sugges...          0
1            back in miami. waiting to unboard ship           0
2  @misskpey awwww dnt dis brng bak memoriessss, ...          0
3                   ughhh i am so tired blahhhhhhhhh          0
4  @mandagoforth me bad! it's funny though. zacha...          0

### 10. Contraction to Expansion

In [127]:
import json

contractions = json.load(open('data/contractions.json'))

In [128]:
contractions.get("don't")

'do not'

In [129]:
# Dictionary lookup: .get(key, default) returns the expanded word if it exists,
# otherwise it keeps the original word to prevent errors.
x = "don't mess with me. I'm done with this stuff."
[contractions.get(word, word) for word in x.split()]

['do not', 'mess', 'with', 'me.', "I'm", 'done', 'with', 'this', 'stuff.']

In [130]:
[contractions.get(word.lower(), word) for word in x.split()]

['do not', 'mess', 'with', 'me.', 'i am', 'done', 'with', 'this', 'stuff.']

In [131]:
" ".join([contractions.get(word.lower(), word) for word in x.split()])

'do not mess with me. i am done with this stuff.'

In [132]:
df['tweets']=df['tweets'].apply(lambda x: " ".join([contractions.get(word.lower(), word) for word in str(x).split()])) #str(x)is imp as without str python is thinking that it's a method and not string.

In [133]:
df

                                                 tweets  sentiment
0     is bored and wants to watch a movie any sugges...          0
1                back in miami. waiting to unboard ship          0
2     @misskpey awwww dnt this bring back at keyboar...          0
3                      ughhh i am so tired blahhhhhhhhh          0
4     @mandagoforth me bad! it is funny though. zach...          0
...                                                 ...        ...
3995                                   i just graduated          1
3996            templating works; it all has to be done          1
3997                    mommy just brought me starbucks          1
3998  @omarepps watching you on a house re-run...lov...          1
3999  thanks for trying to make me smile i will make...          1

[4000 rows x 2 columns]

In [134]:
df[df['tweets'].str.contains("don't")]

                                                 tweets  sentiment
482   making myself ready for school...don't feel li...          0
1259  @dougiemcfly own,don't do that,i'm sure it was...          0
3729  @worldofhiglet i do not think it makes you see...          1

### 11. Count and Remove Emails

In [135]:
x = 'contact me at rutujakumbhar@gmail.com and info@rutuja@gmail.com'

pattern = r'\w+@\w+.\w+'
result = re.findall(pattern=pattern, string=x)
print(result)

['rutujakumbhar@gmail.com', 'info@rutuja@gmail']

In [136]:
x = 'contact me at rutujakumbhar@gmail.com and info@rutuja@gmail.co.in'

pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
result = re.findall(pattern=pattern, string=x)
print(result)

['rutujakumbhar@gmail.com', 'rutuja@gmail.co.in']

In [137]:
df['emails'] = df['emails'] =df['tweets'].apply(lambda x: ",".join(re.findall(pattern=pattern, string=x)))

In [138]:
df['emails'].value_counts()

emails
                               3999
markbradbury_16@hotmail.com       1
Name: count, dtype: int64

In [139]:
x = ''
x.count(',')+1 if len(x)>0 else 0

0

In [140]:
df['emails'].value_counts()

emails
                               3999
markbradbury_16@hotmail.com       1
Name: count, dtype: int64

In [141]:
df['emails_count'] = df['emails'].apply(lambda x: x.count(',')+1 if len(x)>0 else 0)

In [142]:
df['emails_count'].value_counts()

emails_count
0    3999
1       1
Name: count, dtype: int64

In [143]:
df['tweets'] = df['tweets'].apply(lambda x: re.sub(pattern, '', x))

In [144]:
df.head()

,tweets,sentiment,emails,emails_count
0,is bored and wants to watch a movie any sugges...,0,,0
1,back in miami. waiting to unboard ship,0,,0
2,@misskpey awwww dnt this bring back at keyboar...,0,,0
3,ughhh i am so tired blahhhhhhhhh,0,,0
4,@mandagoforth me bad! it is funny though. zach...,0,,0

### 12. Count and Remove URLs

In [145]:
x='Check this link: https://rutujakumbhar.com and www.rutujakumbhar.com'
pattern=r"http\S+|www\.\S+"
re.findall(pattern,x)

['https://rutujakumbhar.com', 'www.rutujakumbhar.com']

In [146]:
df['urls']=df['tweets'].apply(lambda x: re.findall(pattern,x))

In [147]:
df['urls'].value_counts()
df['urls_count']=df['urls'].apply(lambda x: len(x))

In [148]:
df[df['urls_count']>0].head()

,tweets,sentiment,emails,emails_count,urls,urls_count
16,@brianquest i made 1 fo you 2: http://bit.ly/e...,0,,0,[http://bit.ly/eid8a],1
98,heading to work http://twitpic.com/4eojz,0,,0,[http://twitpic.com/4eojz],1
99,@blondeblogger http://twitpic.com/4w8hk - i am...,0,,0,[http://twitpic.com/4w8hk],1
144,i miss you â« http://blip.fm/~8lc2f,0,,0,[http://blip.fm/~8lc2f],1
183,photo: miss germany http://tumblr.com/xf825f012,0,,0,[http://tumblr.com/xf825f012],1

In [149]:
df['tweets']=df['tweets'].apply(lambda x: re.sub(pattern,'',x))

In [150]:
df[df['urls_count']>0].head()

,tweets,sentiment,emails,emails_count,urls,urls_count
16,@brianquest i made 1 fo you 2: i tried but it...,0,,0,[http://bit.ly/eid8a],1
98,heading to work,0,,0,[http://twitpic.com/4eojz],1
99,@blondeblogger - i am so sad this is so blurry!,0,,0,[http://twitpic.com/4w8hk],1
144,i miss you â«,0,,0,[http://blip.fm/~8lc2f],1
183,photo: miss germany,0,,0,[http://tumblr.com/xf825f012],1

### 13. Remove RT (Retweet)

In [ ]:
#Retweet